name: Excel Diff and Report

on:
  push:
    branches:
      - develop # 変更するブランチを指定（例: mainブランチ）

jobs:
  excel_diff:
    runs-on: windows-latest
    permissions:  # プッシュ権限を明示的に設定
      contents: write
    steps:
    # 1. リポジトリのチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # 直近の2コミットを取得

    # 2. ChocolateyでWinMergeをインストール
    - name: Install WinMerge using Chocolatey
      run: choco install winmerge -y

    # # 3. 差分比較を実行するバッチスクリプトの作成
    # - name: Create diff report batch script
    #   run: |
    #     echo @echo off > compare_excel.bat
    #     echo set FILE1=%1 > compare_excel.bat
    #     echo set FILE2=%2 >> compare_excel.bat
    #     echo set REPORT=diff_report.html >> compare_excel.bat
    #     echo WinMergeU.exe %FILE1% %FILE2% /e /u /or %REPORT% >> compare_excel.bat

    # 2. 現在のコミットのファイルを保存
    - name: Save current files
      run: |
        mkdir current_files
        git ls-tree --name-only HEAD > current_files/files_list.txt
        foreach ($file in Get-Content current_files/files_list.txt) {
          cp $file current_files/
        }

    # 3. 前のコミットにチェックアウトしてファイルを取得
    - name: Checkout previous commit files
      run: |
        git checkout HEAD^
        mkdir previous_files
        foreach ($file in Get-Content current_files/files_list.txt) {
          if (Test-Path $file) {
            cp $file previous_files/
          }
        }

    # 4. `diff_report.html` を削除
    - name: Remove existing diff_report.html
      run: |
        if (Test-Path -Path "$PWD\diff_report.html") {
          Remove-Item -Path "$PWD\diff_report.html"
          Write-Host "Previous diff_report.html removed."
        }

    # 5. Excelファイルの差分を比較 (PowerShellで実行)
    - name: Compare Excel files and generate report
      run: |
        $currentFiles = Get-ChildItem -Path "current_files" -Filter "*.xlsx"
        foreach ($file in $currentFiles) {
          $fileName = $file.Name
          $prevFile = "previous_files\$fileName"
          echo "fileName = $fileName"
          echo "prevFile = $prevFile"
          if (Test-Path $prevFile) {
            Start-Process "WinMergeU.exe" -ArgumentList "$prevFile", "$file.FullName", "/x", "/u", "/or $PWD\diff_report.html"
          }
        }

        # diff_report.html が生成されていない場合、空のファイルを作成
        if (-not (Test-Path -Path "diff_report.html")) {
          Write-Host "diff_report.html was not generated, creating an empty file."
          Set-Content -Path "$PWD\diff_report.html" -Value "<html><body><p>No differences found.</p></body></html>"
        }

    # 6. レポートをGitにコミット
    - name: Commit diff report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKENを設定
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add diff_report.html
        git commit -m "Add Excel diff report"
        git pull origin develop
        git push origin HEAD:develop
