name: Excel Diff and Report

on:
  push:
    branches:
      - develop # 変更するブランチを指定（例: mainブランチ）

jobs:
  excel_diff:
    runs-on: windows-latest
    permissions:  # プッシュ権限を明示的に設定
      contents: write
    steps:
    # 1. リポジトリのチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # 直近の2コミットを取得

    # 2. ChocolateyでWinMergeをインストール
    - name: Install WinMerge using Chocolatey
      run: choco install winmerge -y

    # 3. 差分比較を実行するバッチスクリプトの作成
    - name: Create diff report batch script
      run: |
        echo @echo off > compare_excel.bat
        echo set FILE1=%1 > compare_excel.bat
        echo set FILE2=%2 >> compare_excel.bat
        echo set REPORT=diff_report.html >> compare_excel.bat
        echo WinMergeU.exe %FILE1% %FILE2% /e /u /or %REPORT% >> compare_excel.bat

    # 4. 変更されたファイルのリストを取得
    - name: Get changed files
      id: get_changed_files
      run: |
        git diff --name-only HEAD^ HEAD > changed_files.txt

    # 4. `diff_report.html` を削除
    - name: Remove existing diff_report.html
      run: |
        if (Test-Path -Path "$PWD\diff_report.html") {
          Remove-Item -Path "$PWD\diff_report.html"
          Write-Host "Previous diff_report.html removed."
        }

    # 5. Excelファイルの差分を比較
    - name: Compare Excel files and generate report
      run: |
        $changedFiles = Get-Content -Path "changed_files.txt"
        foreach ($file in $changedFiles) {
          if ($file -like "*.xlsx") {
            Start-Process "WinMergeU.exe" -ArgumentList "$file", "HEAD^ --", "/or diff_report.html"
          }
        }
        if (-not $reportGenerated) {
          Write-Host "diff_report.html was not generated, creating an empty file."
          New-Item -Path "$PWD\diff_report.html" -ItemType File
          Add-Content -Path "$PWD\diff_report.html" -Value "<html><body><p>No differences found.</p></body></html>"
        }
        

    # 6. レポートをGitにコミット
    - name: Commit diff report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKENを設定
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add diff_report.html
        git commit -m "Add Excel diff report"
        git push
